language: python
python:
     - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
     - PLATFORMIO_CI_SRC=src/mqtt-gateway-with-temp.ino

install:
    - pip install -U platformio

    - wget https://github.com/marvinroger/homie-esp8266/archive/develop.zip -O /tmp/homie2.zip
    - unzip /tmp/homie2.zip -d /tmp

script:
    - platformio ci --lib="/tmp/homie-esp8266-develop" --board=d1_mini
