language: python
python:
     - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio

    - wget https://github.com/marvinroger/homie-esp8266/archive/develop.zip -O /tmp/homie2.zip
    - unzip /tmp/homie2.zip -d /tmp

script:
    - platformio ci --lib="/tmp/homie2" --board=d1_mini
